/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./templates/**/*.html", "./resources/js/**/*.js", "./static/js/**/*.js"],
  safelist: [
    "badge-emerald",
    "badge-amber",
    "badge-red",
    "badge-slate",
    "badge-blue",
    "badge-green",
    "modal-card",
    "rounded-lg",
    "bg-white",
    "shadow-xl",
    "dark:bg-slate-800",
    "dark:shadow-black/40",
    "fixed",
    "inset-0",
    "z-50",
    "flex",
    "items-center",
    "justify-center",
    "bg-slate-900/50",
    "p-4",
    "w-full",
    "max-w-sm",
    "p-6",
    "text-sm",
    "text-slate-700",
    "dark:text-slate-200",
    "mt-5",
    "justify-end",
    "gap-2",
    "btn-primary",
    "btn-danger",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: "rgb(var(--brand-50) / <alpha-value>)",
          100: "rgb(var(--brand-100) / <alpha-value>)",
          200: "rgb(var(--brand-200) / <alpha-value>)",
          300: "rgb(var(--brand-300) / <alpha-value>)",
          400: "rgb(var(--brand-400) / <alpha-value>)",
          500: "rgb(var(--brand-500) / <alpha-value>)",
          600: "rgb(var(--brand-600) / <alpha-value>)",
          700: "rgb(var(--brand-700) / <alpha-value>)",
          800: "rgb(var(--brand-800) / <alpha-value>)",
          900: "rgb(var(--brand-900) / <alpha-value>)",
          950: "rgb(var(--brand-950) / <alpha-value>)",
        },
      },
    },
  },
  plugins: [],
};
