/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./templates/**/*.html", "./resources/js/**/*.js", "./static/js/**/*.js"],
  safelist: [
    "badge-emerald",
    "badge-amber",
    "badge-red",
    "badge-slate",
    "badge-blue",
    "badge-green",
    "modal-card",
    "rounded-lg",
    "bg-white",
    "shadow-xl",
    "dark:bg-slate-800",
    "dark:shadow-black/40",
    "fixed",
    "inset-0",
    "z-50",
    "flex",
    "items-center",
    "justify-center",
    "bg-slate-900/50",
    "p-4",
    "w-full",
    "max-w-sm",
    "p-6",
    "text-sm",
    "text-slate-700",
    "dark:text-slate-200",
    "mt-5",
    "justify-end",
    "gap-2",
    "btn-primary",
    "btn-danger",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: "#f0fdf4",
          100: "#dcfce7",
          200: "#bbf7d0",
          300: "#86efac",
          400: "#4ade80",
          500: "#22c55e",
          600: "#16a34a",
          700: "#15803d",
          800: "#166534",
          900: "#14532d",
          950: "#052e16",
        },
      },
    },
  },
  plugins: [],
};
