"""initial schema

Revision ID: 15da357806df
Revises:
Create Date: 2026-09-24 12:18:25.784793

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15da357806df"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kb_categories",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_categories_pkey")),
    )
    with op.batch_alter_table("kb_categories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("kb_categories_slug_idx"), ["slug"], unique=True)

    op.create_table(
        "kb_tags",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_tags_pkey")),
    )
    with op.batch_alter_table("kb_tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("kb_tags_slug_idx"), ["slug"], unique=True)

    op.create_table(
        "ticket_categories",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("ticket_categories_pkey")),
    )
    with op.batch_alter_table("ticket_categories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ticket_categories_slug_idx"), ["slug"], unique=True)

    op.create_table(
        "users",
        sa.Column("google_id", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("avatar", sa.String(length=500), nullable=True),
        sa.Column("role", sa.Enum("user", "agent", "admin", name="user_role", native_enum=False, length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("users_email_idx"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("users_google_id_idx"), ["google_id"], unique=True)

    op.create_table(
        "kb_articles",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Enum("draft", "published", "archived", name="kb_article_status", native_enum=False, length=50), nullable=False),
        sa.Column("visibility", sa.Enum("public", "internal", name="kb_article_visibility", native_enum=False, length=50), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("kb_articles_author_id_fkey")),
        sa.ForeignKeyConstraint(["category_id"], ["kb_categories.id"], name=op.f("kb_articles_category_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_articles_pkey")),
    )
    with op.batch_alter_table("kb_articles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("kb_articles_author_id_idx"), ["author_id"], unique=False)
        batch_op.create_index(batch_op.f("kb_articles_category_id_idx"), ["category_id"], unique=False)
        batch_op.create_index(batch_op.f("kb_articles_slug_idx"), ["slug"], unique=True)
        batch_op.create_index("kb_articles_status_updated_idx", ["status", "updated_at"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("link", sa.String(length=255), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("notifications_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("notifications_pkey")),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("notifications_user_id_idx"), ["user_id"], unique=False)
        batch_op.create_index("notifications_user_read_idx", ["user_id", "is_read"], unique=False)

    op.create_table(
        "tickets",
        sa.Column("ticket_number", sa.String(length=30), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("requester_id", sa.Uuid(), nullable=False),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status", sa.Enum("open", "pending", "in_progress", "resolved", "closed", name="ticket_status", native_enum=False, length=50), nullable=False
        ),
        sa.Column("priority", sa.Enum("low", "normal", "high", "urgent", name="ticket_priority", native_enum=False, length=50), nullable=False),
        sa.Column("source", sa.Enum("web", "email", name="ticket_source", native_enum=False, length=50), nullable=False),
        sa.Column("sla_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["assignee_id"], ["users.id"], name=op.f("tickets_assignee_id_fkey")),
        sa.ForeignKeyConstraint(["category_id"], ["ticket_categories.id"], name=op.f("tickets_category_id_fkey")),
        sa.ForeignKeyConstraint(["requester_id"], ["users.id"], name=op.f("tickets_requester_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("tickets_pkey")),
    )
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("tickets_assignee_id_idx"), ["assignee_id"], unique=False)
        batch_op.create_index(batch_op.f("tickets_category_id_idx"), ["category_id"], unique=False)
        batch_op.create_index(batch_op.f("tickets_requester_id_idx"), ["requester_id"], unique=False)
        batch_op.create_index(batch_op.f("tickets_sla_due_at_idx"), ["sla_due_at"], unique=False)
        batch_op.create_index("tickets_status_updated_idx", ["status", "updated_at"], unique=False)
        batch_op.create_index(batch_op.f("tickets_ticket_number_idx"), ["ticket_number"], unique=True)

    op.create_table(
        "activity_logs",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("ticket_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("old_data", sa.JSON(), nullable=True),
        sa.Column("new_data", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], name=op.f("activity_logs_ticket_id_fkey")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("activity_logs_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("activity_logs_pkey")),
    )
    with op.batch_alter_table("activity_logs", schema=None) as batch_op:
        batch_op.create_index("activity_logs_entity_idx", ["entity_type", "entity_id"], unique=False)
        batch_op.create_index(batch_op.f("activity_logs_ticket_id_idx"), ["ticket_id"], unique=False)
        batch_op.create_index(batch_op.f("activity_logs_user_id_idx"), ["user_id"], unique=False)

    op.create_table(
        "kb_article_feedback",
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("is_helpful", sa.Boolean(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["kb_articles.id"], name=op.f("kb_article_feedback_article_id_fkey")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("kb_article_feedback_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_article_feedback_pkey")),
        sa.UniqueConstraint("article_id", "user_id", name="uq_kb_article_feedback_article_user"),
    )
    with op.batch_alter_table("kb_article_feedback", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("kb_article_feedback_article_id_idx"), ["article_id"], unique=False)

    op.create_table(
        "kb_article_revisions",
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("editor_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["kb_articles.id"], name=op.f("kb_article_revisions_article_id_fkey")),
        sa.ForeignKeyConstraint(["editor_id"], ["users.id"], name=op.f("kb_article_revisions_editor_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_article_revisions_pkey")),
        sa.UniqueConstraint("article_id", "revision_no", name="uq_kb_article_revisions_article_revision"),
    )
    with op.batch_alter_table("kb_article_revisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("kb_article_revisions_article_id_idx"), ["article_id"], unique=False)

    op.create_table(
        "kb_article_tags",
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["kb_articles.id"], name=op.f("kb_article_tags_article_id_fkey")),
        sa.ForeignKeyConstraint(["tag_id"], ["kb_tags.id"], name=op.f("kb_article_tags_tag_id_fkey")),
        sa.PrimaryKeyConstraint("article_id", "tag_id", name=op.f("kb_article_tags_pkey")),
    )
    op.create_table(
        "kb_attachments",
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["kb_articles.id"], name=op.f("kb_attachments_article_id_fkey")),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], name=op.f("kb_attachments_uploaded_by_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_attachments_pkey")),
    )
    with op.batch_alter_table("kb_attachments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("kb_attachments_article_id_idx"), ["article_id"], unique=False)

    op.create_table(
        "ticket_comments",
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_internal", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("ticket_comments_author_id_fkey")),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], name=op.f("ticket_comments_ticket_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("ticket_comments_pkey")),
    )
    with op.batch_alter_table("ticket_comments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ticket_comments_author_id_idx"), ["author_id"], unique=False)
        batch_op.create_index(batch_op.f("ticket_comments_ticket_id_idx"), ["ticket_id"], unique=False)

    op.create_table(
        "ticket_attachments",
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("comment_id", sa.Uuid(), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["comment_id"], ["ticket_comments.id"], name=op.f("ticket_attachments_comment_id_fkey")),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], name=op.f("ticket_attachments_ticket_id_fkey")),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], name=op.f("ticket_attachments_uploaded_by_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("ticket_attachments_pkey")),
    )
    with op.batch_alter_table("ticket_attachments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ticket_attachments_comment_id_idx"), ["comment_id"], unique=False)
        batch_op.create_index(batch_op.f("ticket_attachments_ticket_id_idx"), ["ticket_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ticket_attachments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ticket_attachments_ticket_id_idx"))
        batch_op.drop_index(batch_op.f("ticket_attachments_comment_id_idx"))

    op.drop_table("ticket_attachments")
    with op.batch_alter_table("ticket_comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ticket_comments_ticket_id_idx"))
        batch_op.drop_index(batch_op.f("ticket_comments_author_id_idx"))

    op.drop_table("ticket_comments")
    with op.batch_alter_table("kb_attachments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("kb_attachments_article_id_idx"))

    op.drop_table("kb_attachments")
    op.drop_table("kb_article_tags")
    with op.batch_alter_table("kb_article_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("kb_article_revisions_article_id_idx"))

    op.drop_table("kb_article_revisions")
    with op.batch_alter_table("kb_article_feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("kb_article_feedback_article_id_idx"))

    op.drop_table("kb_article_feedback")
    with op.batch_alter_table("activity_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("activity_logs_user_id_idx"))
        batch_op.drop_index(batch_op.f("activity_logs_ticket_id_idx"))
        batch_op.drop_index("activity_logs_entity_idx")

    op.drop_table("activity_logs")
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("tickets_ticket_number_idx"))
        batch_op.drop_index("tickets_status_updated_idx")
        batch_op.drop_index(batch_op.f("tickets_sla_due_at_idx"))
        batch_op.drop_index(batch_op.f("tickets_requester_id_idx"))
        batch_op.drop_index(batch_op.f("tickets_category_id_idx"))
        batch_op.drop_index(batch_op.f("tickets_assignee_id_idx"))

    op.drop_table("tickets")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index("notifications_user_read_idx")
        batch_op.drop_index(batch_op.f("notifications_user_id_idx"))

    op.drop_table("notifications")
    with op.batch_alter_table("kb_articles", schema=None) as batch_op:
        batch_op.drop_index("kb_articles_status_updated_idx")
        batch_op.drop_index(batch_op.f("kb_articles_slug_idx"))
        batch_op.drop_index(batch_op.f("kb_articles_category_id_idx"))
        batch_op.drop_index(batch_op.f("kb_articles_author_id_idx"))

    op.drop_table("kb_articles")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("users_google_id_idx"))
        batch_op.drop_index(batch_op.f("users_email_idx"))

    op.drop_table("users")
    with op.batch_alter_table("ticket_categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ticket_categories_slug_idx"))

    op.drop_table("ticket_categories")
    with op.batch_alter_table("kb_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("kb_tags_slug_idx"))

    op.drop_table("kb_tags")
    with op.batch_alter_table("kb_categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("kb_categories_slug_idx"))

    op.drop_table("kb_categories")
    # ### end Alembic commands ###
