"""add query indexes

Revision ID: 2c8c9cc18e0b
Revises: 212f92b322b9
Create Date: 2026-09-24 13:10:38.155725

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c8c9cc18e0b"
down_revision: str | None = "212f92b322b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_logs", schema=None) as batch_op:
        batch_op.create_index("activity_logs_created_idx", ["created_at"], unique=False)

    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index("notifications_user_read_created_idx", ["user_id", "is_read", "created_at"], unique=False)

    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.create_index("tickets_assignee_status_idx", ["assignee_id", "status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.drop_index("tickets_assignee_status_idx")

    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index("notifications_user_read_created_idx")

    with op.batch_alter_table("activity_logs", schema=None) as batch_op:
        batch_op.drop_index("activity_logs_created_idx")

    # ### end Alembic commands ###
