"""drop ticket source

Revision ID: ec9c345f58ab
Revises: 744111df4fb2
Create Date: 2026-09-28 10:27:40.267630

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec9c345f58ab"
down_revision: str | None = "744111df4fb2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.drop_column("source")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "source",
                sa.Enum("web", "email", name="ticket_source", native_enum=False, length=50),
                nullable=False,
                server_default="web",
            )
        )
        batch_op.alter_column("source", server_default=None)

    # ### end Alembic commands ###
