// Maps a stable project icon name (used in templates as icon("name")) to the
// corresponding Lucide file in node_modules/lucide-static/icons/<file>.svg.
// Keep project names stable so call sites never change when Lucide renames a file.
export default {
  home: "house",
  users: "users",
  "book-open": "book-open",
  ticket: "ticket",
  document: "file-text",
  clipboard: "clipboard",
  chart: "chart-no-axes-column",
  activity: "activity",
  settings: "settings",
  logout: "log-out",
  menu: "menu",
  x: "x",
  plus: "plus",
  search: "search",
  list: "list",
  pencil: "pencil",
  trash: "trash-2",
  check: "check",
  "check-circle": "circle-check",
  "x-circle": "circle-x",
  warning: "triangle-alert",
  calendar: "calendar",
  clock: "clock",
  image: "image",
  download: "download",
  folder: "folder",
  tag: "tags",
  paperclip: "paperclip",
  "life-buoy": "life-buoy",
  eye: "eye",
  "message-circle": "message-circle",
  filter: "filter",
  "external-link": "external-link",
  sun: "sun",
  moon: "moon",
  monitor: "monitor",
  bell: "bell",
  refresh: "refresh-cw",
  building: "building-2",
  lock: "lock",
  "chevron-down": "chevron-down",
  "chevron-left": "chevron-left",
  "chevron-right": "chevron-right",
  mail: "mail",
  phone: "phone",
  "map-pin": "map-pin",
};
